/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\jlebr\\Desktop\\laravel-memos\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7f4dd718",
    path: "/memos/acceder-a-une-requete-dans-une-url-avec-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f4dd718").then(next)
    },
  },
  {
    name: "v-9e14a9c4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e14a9c4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-73683d8f",
    path: "/memos/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73683d8f").then(next)
    },
  },
  {
    path: "/memos/index.html",
    redirect: "/memos/"
  },
  {
    name: "v-1bae6b98",
    path: "/memos/accesseurs-et-mutateurs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bae6b98").then(next)
    },
  },
  {
    name: "v-579bc774",
    path: "/memos/conventions-de-nommage-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-579bc774").then(next)
    },
  },
  {
    name: "v-3a67ee48",
    path: "/memos/c-est-quoi-un-modele-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a67ee48").then(next)
    },
  },
  {
    name: "v-192ab510",
    path: "/memos/afficher-des-donnees-dans-une-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-192ab510").then(next)
    },
  },
  {
    name: "v-373fef22",
    path: "/memos/creer-des-routes-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-373fef22").then(next)
    },
  },
  {
    name: "v-79bb1b58",
    path: "/memos/creer-des-layouts-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79bb1b58").then(next)
    },
  },
  {
    name: "v-48b59890",
    path: "/memos/creer-et-retourner-des-reponses.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48b59890").then(next)
    },
  },
  {
    name: "v-5e6cf518",
    path: "/memos/creer-un-controleur-sur-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e6cf518").then(next)
    },
  },
  {
    name: "v-31b31e98",
    path: "/memos/creer-un-modele-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31b31e98").then(next)
    },
  },
  {
    name: "v-6fd9aa90",
    path: "/memos/eager-loading-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fd9aa90").then(next)
    },
  },
  {
    name: "v-1f1027d8",
    path: "/memos/creer-un-nouveau-projet-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f1027d8").then(next)
    },
  },
  {
    name: "v-b1316ed0",
    path: "/memos/faire-une-requete-vers-la-base-de-donnees.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1316ed0").then(next)
    },
  },
  {
    name: "v-010bac7c",
    path: "/memos/eloquent-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-010bac7c").then(next)
    },
  },
  {
    name: "v-73221810",
    path: "/memos/les-controleurs-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73221810").then(next)
    },
  },
  {
    name: "v-0c8c7818",
    path: "/memos/migration.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c8c7818").then(next)
    },
  },
  {
    name: "v-23467d74",
    path: "/memos/installer-les-prerequis-pour-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23467d74").then(next)
    },
  },
  {
    name: "v-f74abcf8",
    path: "/memos/gerer-le-css-sur-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f74abcf8").then(next)
    },
  },
  {
    name: "v-f1b79d68",
    path: "/memos/pagination-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1b79d68").then(next)
    },
  },
  {
    name: "v-0f9291fa",
    path: "/memos/enregistrer-des-donnees-dans-une-table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f9291fa").then(next)
    },
  },
  {
    name: "v-d5dc8210",
    path: "/memos/se-reperer-dans-une-relation-entre-les-tables.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5dc8210").then(next)
    },
  },
  {
    name: "v-c48dc6d0",
    path: "/memos/query-builder-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c48dc6d0").then(next)
    },
  },
  {
    name: "v-1e4c37d0",
    path: "/memos/supprimer-un-enregistrement-dans-la-base-de-donnees.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e4c37d0").then(next)
    },
  },
  {
    name: "v-6b7b3838",
    path: "/memos/seeding-laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b7b3838").then(next)
    },
  },
  {
    name: "v-706be1b8",
    path: "/memos/se-connecter-a-mysql-et-creer-une-base-de-donnees.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-706be1b8").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]