/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Laravel Memorandum",
  "description": "Quelques mémos, astuces pour le framework Laravel.",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#F05340"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Accéder à une requête dans une url",
      "frontmatter": {},
      "regularPath": "/memos/acceder-a-une-requete-dans-une-url-avec-laravel.html",
      "relativePath": "memos/acceder-a-une-requete-dans-une-url-avec-laravel.md",
      "key": "v-7f4dd718",
      "path": "/memos/acceder-a-une-requete-dans-une-url-avec-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Afficher la requête dans une vue",
          "slug": "afficher-la-requete-dans-une-vue"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/laravel-logo.svg",
        "tagline": "Mémos, astuces, exemples pour la communauté francophone du framework Laravel.",
        "actionText": "Consulter les mémos →",
        "actionLink": "/memos/",
        "footer": "Made by Jo with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-9e14a9c4",
      "path": "/",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/memos/",
      "relativePath": "memos/README.md",
      "key": "v-73683d8f",
      "path": "/memos/",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Afficher des données dynamiquement dans une vue",
      "frontmatter": {},
      "regularPath": "/memos/afficher-des-donnees-dans-une-vue.html",
      "relativePath": "memos/afficher-des-donnees-dans-une-vue.md",
      "key": "v-192ab510",
      "path": "/memos/afficher-des-donnees-dans-une-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Depuis une route",
          "slug": "depuis-une-route"
        },
        {
          "level": 2,
          "title": "Depuis un contrôleur",
          "slug": "depuis-un-controleur"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Les accesseurs et mutateurs",
      "frontmatter": {},
      "regularPath": "/memos/accesseurs-et-mutateurs.html",
      "relativePath": "memos/accesseurs-et-mutateurs.md",
      "key": "v-1bae6b98",
      "path": "/memos/accesseurs-et-mutateurs.html",
      "headers": [
        {
          "level": 2,
          "title": "Définir un accesseur",
          "slug": "definir-un-accesseur"
        },
        {
          "level": 2,
          "title": "Définir un mutateur",
          "slug": "definir-un-mutateur"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "C'est quoi un modèle ?",
      "frontmatter": {},
      "regularPath": "/memos/c-est-quoi-un-modele-laravel.html",
      "relativePath": "memos/c-est-quoi-un-modele-laravel.md",
      "key": "v-3a67ee48",
      "path": "/memos/c-est-quoi-un-modele-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Conventions de nommage Laravel",
      "frontmatter": {},
      "regularPath": "/memos/conventions-de-nommage-laravel.html",
      "relativePath": "memos/conventions-de-nommage-laravel.md",
      "key": "v-579bc774",
      "path": "/memos/conventions-de-nommage-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Le modèle",
          "slug": "le-modele"
        },
        {
          "level": 2,
          "title": "Les contrôleurs",
          "slug": "les-controleurs"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer des routes",
      "frontmatter": {},
      "regularPath": "/memos/creer-des-routes-laravel.html",
      "relativePath": "memos/creer-des-routes-laravel.md",
      "key": "v-373fef22",
      "path": "/memos/creer-des-routes-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Route simple",
          "slug": "route-simple"
        },
        {
          "level": 2,
          "title": "Passer des données à une la route",
          "slug": "passer-des-donnees-a-une-la-route"
        },
        {
          "level": 3,
          "title": "Afficher les données sur une vue",
          "slug": "afficher-les-donnees-sur-une-vue"
        },
        {
          "level": 2,
          "title": "Créer une route type 'posts/mon-premier-post' (paramètres)",
          "slug": "creer-une-route-type-posts-mon-premier-post-parametres"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer des layouts",
      "frontmatter": {},
      "regularPath": "/memos/creer-des-layouts-laravel.html",
      "relativePath": "memos/creer-des-layouts-laravel.md",
      "key": "v-79bb1b58",
      "path": "/memos/creer-des-layouts-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Créer le dossier layouts/",
          "slug": "creer-le-dossier-layouts"
        },
        {
          "level": 2,
          "title": "Utiliser un layout dans une vue",
          "slug": "utiliser-un-layout-dans-une-vue"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer un contrôleur",
      "frontmatter": {},
      "regularPath": "/memos/creer-un-controleur-sur-laravel.html",
      "relativePath": "memos/creer-un-controleur-sur-laravel.md",
      "key": "v-5e6cf518",
      "path": "/memos/creer-un-controleur-sur-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer et retourner des réponses",
      "frontmatter": {},
      "regularPath": "/memos/creer-et-retourner-des-reponses.html",
      "relativePath": "memos/creer-et-retourner-des-reponses.md",
      "key": "v-48b59890",
      "path": "/memos/creer-et-retourner-des-reponses.html",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Démarrer un nouveau projet Laravel",
      "frontmatter": {},
      "regularPath": "/memos/creer-un-nouveau-projet-laravel.html",
      "relativePath": "memos/creer-un-nouveau-projet-laravel.md",
      "key": "v-1f1027d8",
      "path": "/memos/creer-un-nouveau-projet-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Créer un projet",
          "slug": "creer-un-projet"
        },
        {
          "level": 2,
          "title": "Lancer un serveur de développement",
          "slug": "lancer-un-serveur-de-developpement"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Le Eager Loading",
      "frontmatter": {},
      "regularPath": "/memos/eager-loading-laravel.html",
      "relativePath": "memos/eager-loading-laravel.md",
      "key": "v-6fd9aa90",
      "path": "/memos/eager-loading-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer un modèle",
      "frontmatter": {},
      "regularPath": "/memos/creer-un-modele-laravel.html",
      "relativePath": "memos/creer-un-modele-laravel.md",
      "key": "v-31b31e98",
      "path": "/memos/creer-un-modele-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Avec son contrôleur",
          "slug": "avec-son-controleur"
        },
        {
          "level": 2,
          "title": "Avec sa factory",
          "slug": "avec-sa-factory"
        },
        {
          "level": 2,
          "title": "Avec son seeder",
          "slug": "avec-son-seeder"
        },
        {
          "level": 2,
          "title": "Avec toutes les options",
          "slug": "avec-toutes-les-options"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Eloquent",
      "frontmatter": {},
      "regularPath": "/memos/eloquent-laravel.html",
      "relativePath": "memos/eloquent-laravel.md",
      "key": "v-010bac7c",
      "path": "/memos/eloquent-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Enregistrer des données dans une table",
      "frontmatter": {},
      "regularPath": "/memos/enregistrer-des-donnees-dans-une-table.html",
      "relativePath": "memos/enregistrer-des-donnees-dans-une-table.md",
      "key": "v-0f9291fa",
      "path": "/memos/enregistrer-des-donnees-dans-une-table.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Faire une requête (Query Builder)",
      "frontmatter": {},
      "regularPath": "/memos/faire-une-requete-vers-la-base-de-donnees.html",
      "relativePath": "memos/faire-une-requete-vers-la-base-de-donnees.md",
      "key": "v-b1316ed0",
      "path": "/memos/faire-une-requete-vers-la-base-de-donnees.html",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Installer les prérequis pour Laravel",
      "frontmatter": {},
      "regularPath": "/memos/installer-les-prerequis-pour-laravel.html",
      "relativePath": "memos/installer-les-prerequis-pour-laravel.md",
      "key": "v-23467d74",
      "path": "/memos/installer-les-prerequis-pour-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Installer PHP et MySQL (simplement)",
          "slug": "installer-php-et-mysql-simplement"
        },
        {
          "level": 2,
          "title": "Installer Composer",
          "slug": "installer-composer"
        },
        {
          "level": 2,
          "title": "Installer Laravel",
          "slug": "installer-laravel"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Gérer le CSS",
      "frontmatter": {},
      "regularPath": "/memos/gerer-le-css-sur-laravel.html",
      "relativePath": "memos/gerer-le-css-sur-laravel.md",
      "key": "v-f74abcf8",
      "path": "/memos/gerer-le-css-sur-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS Vanilla",
          "slug": "css-vanilla"
        },
        {
          "level": 2,
          "title": "Utiliser SASS",
          "slug": "utiliser-sass"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Migration",
      "frontmatter": {},
      "regularPath": "/memos/migration.html",
      "relativePath": "memos/migration.md",
      "key": "v-0c8c7818",
      "path": "/memos/migration.html",
      "headers": [
        {
          "level": 2,
          "title": "Créer une migration",
          "slug": "creer-une-migration"
        },
        {
          "level": 2,
          "title": "Ajouter une colonne à notre table",
          "slug": "ajouter-une-colonne-a-notre-table"
        },
        {
          "level": 2,
          "title": "Actualiser/Lancer une nouvelle migration",
          "slug": "actualiser-lancer-une-nouvelle-migration"
        },
        {
          "level": 2,
          "title": "Ajouter une NOUVELLE colonne (sans prendre de risque)",
          "slug": "ajouter-une-nouvelle-colonne-sans-prendre-de-risque"
        },
        {
          "level": 2,
          "title": "Commandes migration",
          "slug": "commandes-migration"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Les contrôleurs",
      "frontmatter": {},
      "regularPath": "/memos/les-controleurs-laravel.html",
      "relativePath": "memos/les-controleurs-laravel.md",
      "key": "v-73221810",
      "path": "/memos/les-controleurs-laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "Créer un contrôleur",
          "slug": "creer-un-controleur"
        },
        {
          "level": 2,
          "title": "Modifier un contrôleur",
          "slug": "modifier-un-controleur"
        },
        {
          "level": 2,
          "title": "Définir le contrôleur dans la route",
          "slug": "definir-le-controleur-dans-la-route"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Ne pas échapper les caractères spéciaux",
      "frontmatter": {},
      "regularPath": "/memos/ne-pas-echapper-les-caracteres-speciaux-laravel.html",
      "relativePath": "memos/ne-pas-echapper-les-caracteres-speciaux-laravel.md",
      "key": "v-51340278",
      "path": "/memos/ne-pas-echapper-les-caracteres-speciaux-laravel.html",
      "headers": [
        {
          "level": 3,
          "title": "Ne pas échapper les caractères spéciaux",
          "slug": "ne-pas-echapper-les-caracteres-speciaux"
        }
      ]
    },
    {
      "title": "La pagination sur Laravel",
      "frontmatter": {},
      "regularPath": "/memos/pagination-laravel.html",
      "relativePath": "memos/pagination-laravel.md",
      "key": "v-f1b79d68",
      "path": "/memos/pagination-laravel.html",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Query Builder",
      "frontmatter": {},
      "regularPath": "/memos/query-builder-laravel.html",
      "relativePath": "memos/query-builder-laravel.md",
      "key": "v-c48dc6d0",
      "path": "/memos/query-builder-laravel.html",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Créer une base de donnée",
      "frontmatter": {},
      "regularPath": "/memos/se-connecter-a-mysql-et-creer-une-base-de-donnees.html",
      "relativePath": "memos/se-connecter-a-mysql-et-creer-une-base-de-donnees.md",
      "key": "v-706be1b8",
      "path": "/memos/se-connecter-a-mysql-et-creer-une-base-de-donnees.html",
      "headers": [
        {
          "level": 2,
          "title": "Se connecter à MySQL",
          "slug": "se-connecter-a-mysql"
        },
        {
          "level": 2,
          "title": "Créer une base de donnée",
          "slug": "creer-une-base-de-donnee-2"
        },
        {
          "level": 2,
          "title": "Configurer Laravel et base de donnée",
          "slug": "configurer-laravel-et-base-de-donnee"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Se repérer dans une relation entre des tables",
      "frontmatter": {},
      "regularPath": "/memos/se-reperer-dans-une-relation-entre-les-tables.html",
      "relativePath": "memos/se-reperer-dans-une-relation-entre-les-tables.md",
      "key": "v-d5dc8210",
      "path": "/memos/se-reperer-dans-une-relation-entre-les-tables.html",
      "headers": [
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Seeding",
      "frontmatter": {},
      "regularPath": "/memos/seeding-laravel.html",
      "relativePath": "memos/seeding-laravel.md",
      "key": "v-6b7b3838",
      "path": "/memos/seeding-laravel.html",
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    },
    {
      "title": "Supprimer un enregistrement",
      "frontmatter": {},
      "regularPath": "/memos/supprimer-un-enregistrement-dans-la-base-de-donnees.html",
      "relativePath": "memos/supprimer-un-enregistrement-dans-la-base-de-donnees.md",
      "key": "v-1e4c37d0",
      "path": "/memos/supprimer-un-enregistrement-dans-la-base-de-donnees.html",
      "headers": [
        {
          "level": 2,
          "title": "Ajouter un bouton au formulaire",
          "slug": "ajouter-un-bouton-au-formulaire"
        },
        {
          "level": 2,
          "title": "Ajouter la route",
          "slug": "ajouter-la-route"
        },
        {
          "level": 2,
          "title": "Ajouter la méthode destroy dans le contrôleur",
          "slug": "ajouter-la-methode-destroy-dans-le-controleur"
        },
        {
          "level": 2,
          "title": "Liens utiles",
          "slug": "liens-utiles"
        },
        {
          "level": 2,
          "title": "Retour au sommaire",
          "slug": "retour-au-sommaire"
        }
      ],
      "lastUpdated": "1/28/2021, 11:09:39 AM"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/laravel-logo.svg",
    "repo": "d0tcom/laravel-memos",
    "repoLabel": "Contribuer à Laravel Mémos",
    "editLinks": true,
    "docsRepo": "d0tcom/laravel-memos",
    "docsDir": "docs",
    "editLinkText": "Modifier ou contribuer à cette page.",
    "lastUpdated": "Dernière modification",
    "smoothScroll": true,
    "nextLinks": false,
    "prevLinks": false,
    "nav": [
      {
        "text": "Laravel",
        "link": "/memos/"
      }
    ],
    "sidebar": {
      "/memos/": [
        {
          "title": "Au commencement",
          "collapsable": false,
          "children": [
            "",
            "installer-les-prerequis-pour-laravel",
            "creer-un-nouveau-projet-laravel"
          ]
        },
        {
          "title": "Routing",
          "collapsable": false,
          "children": [
            "creer-des-routes-laravel"
          ]
        },
        {
          "title": "Requêtes",
          "collapsable": false,
          "children": [
            "acceder-a-une-requete-dans-une-url-avec-laravel"
          ]
        },
        {
          "title": "Contrôleurs",
          "collapsable": false,
          "children": [
            "creer-un-controleur-sur-laravel"
          ]
        },
        {
          "title": "Modèles",
          "collapsable": false,
          "children": [
            "c-est-quoi-un-modele-laravel",
            "eloquent-laravel",
            "creer-un-modele-laravel",
            "eager-loading-laravel"
          ]
        },
        {
          "title": "Réponses",
          "collapsable": false,
          "children": [
            "creer-et-retourner-des-reponses"
          ]
        },
        {
          "title": "Views, Blade",
          "collapsable": false,
          "children": [
            "creer-des-layouts-laravel",
            "gerer-le-css-sur-laravel",
            "afficher-des-donnees-dans-une-vue"
          ]
        },
        {
          "title": "Base de donnée",
          "collapsable": false,
          "children": [
            "se-connecter-a-mysql-et-creer-une-base-de-donnees",
            "migration",
            "enregistrer-des-donnees-dans-une-table",
            "supprimer-un-enregistrement-dans-la-base-de-donnees",
            "query-builder-laravel",
            "pagination-laravel",
            "seeding-laravel"
          ]
        },
        {
          "title": "Divers",
          "collapsable": false,
          "children": [
            "conventions-de-nommage-laravel",
            "se-reperer-dans-une-relation-entre-les-tables",
            "ne-pas-echapper-les-caracteres-speciaux-laravel"
          ]
        }
      ]
    }
  }
}